# Generated by Django 5.1.4 on 2025-01-12 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hashtags', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Books',
        ),
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'книга', 'verbose_name_plural': 'книги'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'тег', 'verbose_name_plural': 'теги'},
        ),
    ]
