# Generated by Django 5.1.4 on 2025-01-12 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hashtags', '0002_rename_product_books_alter_books_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Product',
        ),
    ]
