# Generated by Django 5.1.4 on 2025-01-28 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название рецепта')),
                ('description', models.TextField(verbose_name='описание рецепта')),
            ],
            options={
                'verbose_name': 'рецепт',
                'verbose_name_plural': 'рецепты',
            },
        ),
        migrations.CreateModel(
            name='Ingridient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название ингридиента')),
                ('quantity', models.PositiveIntegerField(verbose_name='количество')),
                ('unit', models.CharField(choices=[('граммы', 'граммы'), ('килограммы', 'килограммы'), ('миллилитры', 'миллилитры'), ('литры', 'литры'), ('штуки', 'штуки')], max_length=100, verbose_name='единица измерения')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='cooking.recipe')),
            ],
        ),
    ]
