# Generated by Django 5.1.4 on 2025-01-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0002_rename_ingridient_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('грамм', 'грамм'), ('килограмм', 'килограмм'), ('миллилитр', 'миллилитр'), ('литр', 'литр'), ('штук', 'штук')], max_length=100, verbose_name='единица измерения'),
        ),
    ]
