# Generated by Django 5.1.4 on 2025-01-28 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0003_alter_ingredient_unit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredient',
            new_name='IngredientModel',
        ),
        migrations.RenameModel(
            old_name='Recipe',
            new_name='RecipeModel',
        ),
    ]
