# Generated by Django 5.1.4 on 2025-01-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0005_alter_ingredientmodel_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientmodel',
            name='unit',
            field=models.CharField(choices=[('грамм', 'г'), ('килограмм', 'кг'), ('миллилитр', 'мл'), ('литр', 'л'), ('штук', 'шт')], max_length=100, verbose_name='единица измерения'),
        ),
    ]
