# Generated by Django 5.1.4 on 2025-01-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0002_rename_customworker_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='experience',
            field=models.FloatField(default=1, null=True),
        ),
    ]
