# Generated by Django 5.1.4 on 2025-01-15 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0006_alter_reviews_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя')),
                ('number', models.CharField(max_length=11, verbose_name='телефон')),
                ('mail', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('delivery_address', models.TextField(verbose_name='адрес')),
                ('delivery_choice', models.CharField(choices=[('Самовывоз', 'Самовывоз'), ('Доставка на дом', 'Доставка на дом')], max_length=100, verbose_name='способ доставки')),
                ('payment_method', models.CharField(choices=[('Наличные', 'Наличные'), ('Банковская карта', 'Банковская карта'), ('Денежный перевод', 'Денежный перевод')], max_length=100, verbose_name='способ оплаты')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library.books', verbose_name='книга')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
    ]
