# Generated by Django 5.1.4 on 2025-01-15 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
        ('library', '0006_alter_reviews_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketmodel',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='library.books'),
        ),
    ]
