# Generated by Django 5.1.4 on 2025-01-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_alter_basketmodel_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketmodel',
            name='mail',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
    ]
