# Generated by Django 5.1.4 on 2025-01-15 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_alter_basketmodel_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketmodel',
            name='ordered_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
